export interface Product {
  id: string;
  name: string;
  amount: string;
  price: number;
  image: string;
  description: string;
}

const img = (seed: string) =>
  `https://images.unsplash.com/photo-${seed}?auto=format&fit=crop&w=400&q=70`;

export const products: Product[] = [
  { id: "p1", name: "AEDHERNES 'Meduza'", amount: "30 grammi", price: 1.85, image: img("1518977676601-b53f82aba655"), description: "Magus ja mahlane suhkruhernes, sobib hästi värskelt söömiseks ja külmutamiseks. Varajane sort, kõrge saagikusega. Üks pakike sisaldab ligikaudu 150–180 seemet. Külvake aprilli lõpus otse avamaale ridadesse või kasvuhoonetesse märtsi keskel. Ei vaja toestust, kuna taimed kasvavad kompaktselt ja toetuvad teineteisele. Sobib suurepäraselt ka algajatele aednikele, sest on vastupidav ja ei vaja erilist hoolt." },
  { id: "p2", name: "TOMAT 'Oxheart Orange'", amount: "0,1 grammi", price: 2.95, image: img("1592924357228-91a4daadcfea"), description: "Suur oranž härjasüdame-tüüpi tomat, lihav ja vähese seemnesisaldusega. Suurepärane maitse salatites. Iga vilja kaal võib ulatuda 200–400 grammiseks, mis teeb sellest suurepärase valiku neile, kes armastavad mahla, lihavaid tomateid säilitamiseks. Oranž värvus tuleneb kõrgest beetakaroteeni sisaldusest, mis annab kaunilt kontrastse laigu igale toidulauale. Kõige paremini areneb soojades kasvuhoonetes, kuid annab hea saagi ka päikesepaistelistel suvedel avamaal." },
  { id: "p3", name: "TOMAT 'Red Deuce' F1", amount: "10 seemet", price: 2.45, image: img("1607305387299-a3d9611cd469"), description: "Vastupidav punane hübriidtomat, ühtlase suuruse ja kvaliteediga viljad. Sobib nii kasvuhoonesse kui ka avamaale. F1 hübriid tagab ühtlase idanemise ja tugevamad taimed, mis on automaatselt haigustele vastupidavamad kui avatud tolmeldamise sordid. Viljad kaaluvad keskmiselt 80–120 grammi, mis on ideaalne suurus nii värskelt söömiseks kui ka purkidesse panemiseks. Sort on tuntud oma lühikese vegetatsiooniperioodi poolest, mis võimaldab saaki ka jahedamatel suvedel." },
  { id: "p4", name: "NUIKAPSAS 'Eder' F1", amount: "25 seemet", price: 2.25, image: img("1589927986089-35812388d1f4"), description: "Õrn ja mahlane heleroheline nuikapsas, ei muutu kiududeks. Varajane saak. Selle sordi eripära on paksud, krõbedad lehed, mis säilitavad oma tekstuuri ka lühikese keetmise järel. Sobib eriti hästi wok-roogadele, hautistele ja hapendamiseks, sest happeline keskkond ei muuda lehti limaseks. Külvake märtsi keskel kasvuhoonesse või aprilli lõpus otse peenrale. Esmalt võib seemikuid kasvatada turbapotides, et tagada ühtlane taimede paigutus." },
  { id: "p5", name: "PORRULAUK 'Bulgina'", amount: "100 seemet", price: 1.79, image: "https://picsum.photos/seed/porrulauk/400/400", description: "Keskvalmiv porrulauk pikkade valgete varte ja õrna maitsega. Vastupidav talvele. Bulgina on tuntud ka oma suurepärase säilivuse poolest – koristatud vartel võib kogu talve kuivas ja jahedas kohas hoida ilma erilise ettevalmistuseta. Kõige paremini areneb sügisel külvatud seemnetest, mis talvel aeglasekasvulisena risoomi arendavad ja kevadel kiiresti kasvu alustavad. Sobib nii hautistesse, suppidesse kui ka pirukatele." },
  { id: "p6", name: "KURK 'Ilonara' F1", amount: "20 seemet", price: 3.65, image: img("1604977042946-1eecc30f269e"), description: "Partenokarpne salatkurk, kibedusvaba ja krõmps. Suurepärane saak kogu hooaja vältel. Partenokarpsuse tõttu ei vaja see kurk putukaid tolmeldamiseks, mis tagab viljade moodustumise ka siis, kui ilm on jahe või mesilased ei lenda. Sobib eriti hästi kasvuhoonesse ja rõduaedadesse. Taimed on kompaktsed, kuid annavad pideva saagi kuni sügiseni. Iga seeme on hoolikalt valitud, et tagada maksimaalne idanemisprotsent ja tugevad seemikud." },
  { id: "p7", name: "MELON 'Monica' F1", amount: "5 seemet", price: 3.95, image: img("1571575173700-afb9492e6a50"), description: "Aromaatne ja magus melon, sobib hästi kasvuhoonesse Eesti kliimas. Monica on aretatud just jahedamate suvede jaoks, mistõttu talub ta paremini temperatuurikõikumisi kui traditsioonilised Lõuna-Euroopa melonid. Viljad kaaluvad 1–1,5 kg, on ümarad ja koor on kergelt sooniline. Sisu on oranžikas, mahlane ja intensiivselt lõhnav. Melonite taimed vajavad toestust ja head ventilatsiooni, et vältida seenhaigusi niiskes kliimas." },
  { id: "p8", name: "PORGAND 'Agatha' F1", amount: "1 gramm", price: 2.15, image: img("1582515073490-39981397c445"), description: "Nantese tüüpi porgand, sile ja magus. Hea säilivusega talvel. Agatha on eriline selle poolest, et arendab lühikest, ümmargust juurt, mis ei kahane ja ei muutu kiuliseks ka siis, kui kasvuperiood pikeneb. Sobib hästi rasketele muldadele, kus pikkade porgandite kasvatamine on keeruline. Võib külvata kevadest sügiseni, sest see sort talub ka kergemaid öökülmi. Ideaalne sort aednikule, kes hindab töökindlust ja ühtlast kvaliteeti." },
  { id: "p9", name: "PEET 'Boldor'", amount: "50 seemet", price: 1.95, image: img("1593105544559-ecb03bf76f82"), description: "Erekollane peet, magus ja õrn. Värvi säilitab ka keetmisel. Boldor on saanud aednike seas populaarseks just tänu oma erksale kuldkollasele värvile, mis ei kao isegi pika keetmise või hautamise järel. Magus maitse sobib suurepäraselt salatitele, hautistele ja marineerimiseks. Viljad on ümmargused, keskmise suurusega ja võrdlemisi kiire kasvuga. Saab külvata kevadel ja suvel, et nautida värskeid peete kuni sügiseni." },
  { id: "p10", name: "REDIS 'Celesta' F1", amount: "5 grammi", price: 1.65, image: img("1597362925123-77861d3fbac7"), description: "Ümar punane redis, ei muutu õõnsaks. Sobib külviks kogu suve. Celesta on aretatud spetsiaalselt ühtlase viljastruktuuri jaoks, mistõttu isegi suuremad juured jäävad sisetihkedaks ja mahlakateks. Kuna redis idaneb kiiresti ja kasvab vaid 3–4 nädalat, on see ideaalne kultuur kiireks saagiks aiatekkide vahele või pärast varajaste köögiviljade koristamist. Kasutage seda salatites, võileibadel või marineerituna – maitse on alati krõbe ja värskendav." },
  { id: "p11", name: "SALAT 'Lollo Rossa'", amount: "1 gramm", price: 1.45, image: img("1622205313162-be1d5712a43f"), description: "Lokkis lehtsalat, sügavpunaste lehtedega. Hea kibekas-magus maitse. Lollo Rossa on Itaalia päritolu dekoratiivsalat, mida armastatakse nii maitse kui ka välimuse tõttu. Lehed on lopsakad, kortsulised ja intensiivselt burgundia-punased, mis lisab igale salatile gurmee-tunde. Kasvab hästi nii avamaal kui ka potis rõdul. Kuna see on lehtsalat, saab lehti koristada järk-järgult alates välistest lehtedest, jättes taimed kasvama terveks suveks." },
  { id: "p12", name: "PAPRIKA 'California Wonder'", amount: "15 seemet", price: 2.75, image: img("1583119912267-cc97c911e416"), description: "Klassikaline magus paprika, paksu seinaga viljad. Küpsedes muutub punaseks. California Wonder on juba aastakümneid maailmas üks enimkasvatatud paprikasorte, sest see on ülimalt töökindla ja ühtlase kvaliteediga. Viljad on karbid-kujulised, paksu lihaga ja ideaalsed täitmiseks. Sobib hästi grillimiseks, praadimiseks ja marineerimiseks. Taimed vajavad soojust ja päikest, mistõttu on soovitatav kasvatada kasvuhoones või vähemalt katusealuses kasvukohas." },
  { id: "p13", name: "BASIILIK 'Genovese'", amount: "0,5 grammi", price: 1.55, image: "https://picsum.photos/seed/basiilik/400/400", description: "Klassikaline Itaalia basiilik, ideaalne pesto ja salatite jaoks. Genovese on tuntud oma suurte, läikivate ja intensiivselt aroomivate lehtede poolest, mis on pesto alla Genovese jaoks hädavajalikud. See sort armastab soojust ja päikest, mistõttu on kõige parem kasvatada seda kasvuhoones, rõdul või aknalaual. Ärge unustage õigeaegselt õisikuid ära lõigata, sest see soodustab lehtede kasvu ja takistab taime varakult seemnele minekut. Sobib ka kuivatamiseks ja õlisse panemiseks." },
  { id: "p14", name: "TILL 'Mammoth'", amount: "3 grammi", price: 1.25, image: img("1518977822534-7049a61ee0c2"), description: "Lopsakas till suurte vihtadega, aromaatne. Sobib nii värskeks tarbimiseks kui ka konservimiseks. Mammoth on üks suurimate vihtadega tillsort, mis annab korraga rohkelt materjali. Kasvab kiiresti ja on üks esimesi rohelisi, mida kevadel aias näha võib. Seetõttu sobib suurepäraselt kahe- või isegi kolmekordseks külviks hooaja jooksul. Tillile meeldib niiske pinnas ja osaline vari, kuid ta talub ka päikest. Pärast õitsemist võib tilli seemneid kasutada marinaadides ja leibades." },
  { id: "p15", name: "PETERSELL 'Gigante d'Italia'", amount: "2 grammi", price: 1.35, image: "https://picsum.photos/seed/petersell/400/400", description: "Lehtpetersell suurte tumeroheliste lehtedega, tugeva maitsega. Gigante d'Italia tähendab tõlkes "Itaalia hiiglane", mis iseloomustab täpselt selle sordi lopsakat kasvu ja suuri, kortsulisi lehti. Erinevalt juurpetersellist ei ole selle sordi peamine väärtus risoomis, vaid just lehtedes, mis sobib hästi kastmesse, suppidesse, pestosse ja värskelt tarbida. Lehed on eriti rikkad C-vitamiini ja antioksüdantide poolest, mis teeb sellest tervisliku valiku igale toidulauale." },
  { id: "p16", name: "KÕRVITS 'Uchiki Kuri'", amount: "8 seemet", price: 2.85, image: img("1570586437263-ab629fccc818"), description: "Magus oranž Hokkaido kõrvits, kasvatatav ja hästi säiliv. Pähklise maitsega. Uchiki Kuri, tuntud ka kui "Red Kuri", on Jaapani päritolu väikesekasvuline kõrvits, mille viljad kaaluvad tavaliselt 1–3 kg. Selle eripära on õhuke, söödav koor, mis muudab töötluse eriti lihtsaks – pole vaja koorida. Maitse on intensiivselt magus, kastanjat meenutav, mis sobib suurepäraselt suppidesse, pirukatesse ja püreedesse. Hästi säilib kuivas ja jahedas keldris kogu talve." },
  { id: "p17", name: "SUVIKÕRVITS 'Black Beauty'", amount: "12 seemet", price: 1.95, image: "https://picsum.photos/seed/suvikorvits/400/400", description: "Klassikaline tumeroheline suvikõrvits, viljakas ja kompaktne taim. Black Beauty on aednike seas lemmik juba aastakümneid tänu oma töökindlusele ja rikkalikule saagile. Iga taim võib anda kümneid vilju, kui koristada neid regulaarselt väikese ja keskmise suuruse juures. Sobib grillimiseks, hautamiseks, küpsetamiseks ja isegi magustoitude valmistamiseks, sest suvikõrvitsi maitse on neutraalne ja kohandub hästi erinevate maitseainetega. Ei vaja erilist hoolt – piisab kastmisest ja vahepealsetest väetamistest." },
  { id: "p18", name: "MAITSEHERNES 'Spencer Mix'", amount: "1 gramm", price: 2.55, image: "https://picsum.photos/seed/maitsehernes/400/400", description: "Lõhnav lillsegu suurte lainjate õitega. Ideaalne lõikelilledeks. Spencer Mix sisaldab erinevaid värve – lilla, roosa, valge ja burgundia – mis kõik õitsevad pikkadel vartel ja sobivad suurepäraselt vaasidesse. Maitsehernes on kaunis ronitaim, mis kasvab hästi aiavõre või aiatokil, pakkudes vertikaalset huvitavust aiale. Õied on intensiivselt lõhnavad ja meelitavad ligi mesilasi ning liblikaid, muutes aia elavamaks. Külvake kevadel otse peenrale või alustage seemikutega kasvuhoones." },
  { id: "p19", name: "PÄEVALILL 'Sunspot'", amount: "10 seemet", price: 1.85, image: img("1597848212624-a19eb35e2651"), description: "Kompaktne päevalill, kasvab vaid 60 cm kõrguseks, kuid kannab suurt õit. Sunspot on aretatud just väikesemahuliste aedade ja pottide jaoks, kuna ei vaja toestust ega võta palju ruumi. Sellest hoolimata on õis sama suur ja kuldkollane kui kõrgematel päevalilledel. Sobib suurepäraselt lillepeenrale, äärealadele ja isegi suurtesse lillepottidesse rõdule. Päevalilleseemned meelitavad ligi linde, mistõttu on see tore lisandus ka linnuaeda. Õitseb suve teisest poolest sügiseni." },
  { id: "p20", name: "SAMETLILL 'Durango Mix'", amount: "0,5 grammi", price: 1.65, image: img("1600880292089-90a7e086ee0c"), description: "Suurte täidetud õitega sametlill, õitseb varakult kuni külmadeni. Durango Mix on auhinnatud sort, mis on tuntud oma pikkade ja tugevate varte poolest, mis ei murdu ka vihmases ilmas. Õied on topelt- või pooltopeltkujulised ja meenutavad väikesi gloobuseid, mis on saadaval punase, oranži ja kollase toonis. Sametlilled on vastupidavad ja vähenõudlikud, sobides nii lillepeenardele kui ka pottidesse. Neil on ka looduslikult kahjuritõrjerivad omadused, mistõttu aitavad nad kaitsta teisi taimi." },
];

export const specialOffer = {
  name: "TOMAT 'Tigerella'",
  amount: "20 seemet",
  oldPrice: 3.25,
  newPrice: 1.95,
  image: "https://picsum.photos/seed/ripe-tomato/400/400",
};
