/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UudisedRouteImport } from './routes/uudised'
import { Route as PoodRouteImport } from './routes/pood'
import { Route as OstukorvRouteImport } from './routes/ostukorv'
import { Route as MuugitingimusedRouteImport } from './routes/muugitingimused'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as KassaRouteImport } from './routes/kassa'
import { Route as FirmastRouteImport } from './routes/firmast'
import { Route as AitahRouteImport } from './routes/aitah'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToodeUrlKeyRouteImport } from './routes/toode.$urlKey'

const UudisedRoute = UudisedRouteImport.update({
  id: '/uudised',
  path: '/uudised',
  getParentRoute: () => rootRouteImport,
} as any)
const PoodRoute = PoodRouteImport.update({
  id: '/pood',
  path: '/pood',
  getParentRoute: () => rootRouteImport,
} as any)
const OstukorvRoute = OstukorvRouteImport.update({
  id: '/ostukorv',
  path: '/ostukorv',
  getParentRoute: () => rootRouteImport,
} as any)
const MuugitingimusedRoute = MuugitingimusedRouteImport.update({
  id: '/muugitingimused',
  path: '/muugitingimused',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const KassaRoute = KassaRouteImport.update({
  id: '/kassa',
  path: '/kassa',
  getParentRoute: () => rootRouteImport,
} as any)
const FirmastRoute = FirmastRouteImport.update({
  id: '/firmast',
  path: '/firmast',
  getParentRoute: () => rootRouteImport,
} as any)
const AitahRoute = AitahRouteImport.update({
  id: '/aitah',
  path: '/aitah',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToodeUrlKeyRoute = ToodeUrlKeyRouteImport.update({
  id: '/toode/$urlKey',
  path: '/toode/$urlKey',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aitah': typeof AitahRoute
  '/firmast': typeof FirmastRoute
  '/kassa': typeof KassaRoute
  '/kontakt': typeof KontaktRoute
  '/muugitingimused': typeof MuugitingimusedRoute
  '/ostukorv': typeof OstukorvRoute
  '/pood': typeof PoodRoute
  '/uudised': typeof UudisedRoute
  '/toode/$urlKey': typeof ToodeUrlKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aitah': typeof AitahRoute
  '/firmast': typeof FirmastRoute
  '/kassa': typeof KassaRoute
  '/kontakt': typeof KontaktRoute
  '/muugitingimused': typeof MuugitingimusedRoute
  '/ostukorv': typeof OstukorvRoute
  '/pood': typeof PoodRoute
  '/uudised': typeof UudisedRoute
  '/toode/$urlKey': typeof ToodeUrlKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aitah': typeof AitahRoute
  '/firmast': typeof FirmastRoute
  '/kassa': typeof KassaRoute
  '/kontakt': typeof KontaktRoute
  '/muugitingimused': typeof MuugitingimusedRoute
  '/ostukorv': typeof OstukorvRoute
  '/pood': typeof PoodRoute
  '/uudised': typeof UudisedRoute
  '/toode/$urlKey': typeof ToodeUrlKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aitah'
    | '/firmast'
    | '/kassa'
    | '/kontakt'
    | '/muugitingimused'
    | '/ostukorv'
    | '/pood'
    | '/uudised'
    | '/toode/$urlKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aitah'
    | '/firmast'
    | '/kassa'
    | '/kontakt'
    | '/muugitingimused'
    | '/ostukorv'
    | '/pood'
    | '/uudised'
    | '/toode/$urlKey'
  id:
    | '__root__'
    | '/'
    | '/aitah'
    | '/firmast'
    | '/kassa'
    | '/kontakt'
    | '/muugitingimused'
    | '/ostukorv'
    | '/pood'
    | '/uudised'
    | '/toode/$urlKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AitahRoute: typeof AitahRoute
  FirmastRoute: typeof FirmastRoute
  KassaRoute: typeof KassaRoute
  KontaktRoute: typeof KontaktRoute
  MuugitingimusedRoute: typeof MuugitingimusedRoute
  OstukorvRoute: typeof OstukorvRoute
  PoodRoute: typeof PoodRoute
  UudisedRoute: typeof UudisedRoute
  ToodeUrlKeyRoute: typeof ToodeUrlKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uudised': {
      id: '/uudised'
      path: '/uudised'
      fullPath: '/uudised'
      preLoaderRoute: typeof UudisedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pood': {
      id: '/pood'
      path: '/pood'
      fullPath: '/pood'
      preLoaderRoute: typeof PoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ostukorv': {
      id: '/ostukorv'
      path: '/ostukorv'
      fullPath: '/ostukorv'
      preLoaderRoute: typeof OstukorvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/muugitingimused': {
      id: '/muugitingimused'
      path: '/muugitingimused'
      fullPath: '/muugitingimused'
      preLoaderRoute: typeof MuugitingimusedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kassa': {
      id: '/kassa'
      path: '/kassa'
      fullPath: '/kassa'
      preLoaderRoute: typeof KassaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firmast': {
      id: '/firmast'
      path: '/firmast'
      fullPath: '/firmast'
      preLoaderRoute: typeof FirmastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aitah': {
      id: '/aitah'
      path: '/aitah'
      fullPath: '/aitah'
      preLoaderRoute: typeof AitahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toode/$urlKey': {
      id: '/toode/$urlKey'
      path: '/toode/$urlKey'
      fullPath: '/toode/$urlKey'
      preLoaderRoute: typeof ToodeUrlKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AitahRoute: AitahRoute,
  FirmastRoute: FirmastRoute,
  KassaRoute: KassaRoute,
  KontaktRoute: KontaktRoute,
  MuugitingimusedRoute: MuugitingimusedRoute,
  OstukorvRoute: OstukorvRoute,
  PoodRoute: PoodRoute,
  UudisedRoute: UudisedRoute,
  ToodeUrlKeyRoute: ToodeUrlKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
